apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: get-image-tag
spec:
  params:
    - name: WORKING_DIR
      type: string
  results:
    - description: Current image tag in WORKING_DIR
      name: image-tag
  steps:
    - image: 'k8s.gcr.io/kustomize/kustomize:v3.8.7'
      name: get-staging-image
      resources: {}
      script: >
        /app/kustomize build $(params.WORKING_DIR) | grep "image:" | awk -F ":"
        '{print $3}' | xargs echo -n > /tekton/results/image-tag
      workingDir: $(workspaces.output.path)
  workspaces:
    - description: The workspace consisting of the config repo
      name: output
