apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: maven
  labels:
    app.kubernetes.io/version: "0.4.0"
    app.kubernetes.io/part-of: tekton-catalog
spec:
  description: >-
    This Task can be used to run a Maven build.
    It caches dependencies in a persistent workspace to speed up subsequent runs.
  workspaces:
    - name: source
      description: The source code to build.
    - name: maven-repo
      description: Persistent cache for Maven dependencies (~/.m2/repository)
  params:
    - name: GOALS
      type: array
      description: The Maven goals to run
      default:
        - package
    - name: MAVEN_IMAGE
      type: string
      description: The Maven base image
      default: gcr.io/cloud-builders/mvn
    - name: CONTEXT_DIR
      type: string
      description: The context directory within the source workspace
      default: .
    - name: MAVEN_ARGS_APPEND
      type: string
      description: Additional arguments to pass to Maven
      default: ""
  steps:
    - name: mvn
      image: "$(params.MAVEN_IMAGE)"
      workingDir: "$(workspaces.source.path)/$(params.CONTEXT_DIR)"
      command:
        - mvn
      args:
        - -Dmaven.repo.local=$(workspaces.maven-repo.path)
        - "$(params.MAVEN_ARGS_APPEND)"
        - "$(params.GOALS)"