kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: hello-world-maven
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: gp2-csi
  volumeMode: Filesystem