---
- name: Add cert-manager-operator namespace
  kubernetes.core.k8s:
    state: present
    src: cert-manager-namespace.yaml

- name: Add cert-manager-operator-group
  kubernetes.core.k8s:
    state: present
    src: cert-manager-operator-group.yaml

- name: Add cert-manager subscription
  kubernetes.core.k8s:
    state: present
    src: cert-manager-subscription.yaml
  register: certmanager

- name: Add flux-operator namespace
  kubernetes.core.k8s:
    state: present
    src: flux-namespace.yaml

- name: Add flux-operator-group
  kubernetes.core.k8s:
    state: present
    src: flux-operator-group.yaml

- name: Add flux subscription
  kubernetes.core.k8s:
    state: present
    src: flux-subscription.yaml
  register: flux

- name: Add rhacs-operator namespace
  kubernetes.core.k8s:
    state: present
    src: rhacs-operator-namespace.yaml

- name: Add rhacs-operator-group
  kubernetes.core.k8s:
    state: present
    src: rhacs-operator-group.yaml

- name: Add rhacs operator subscription
  kubernetes.core.k8s:
    state: present
    src: rhacs-subscription.yaml
  register: rhacs

- name: Add pipelines subscription
  kubernetes.core.k8s:
    state: present
    src: pipelines-subscription.yaml
  register: pipelines

- name: Wait 2 minute for operator install
  ansible.builtin.wait_for:
    timeout: 120
  delegate_to: localhost
  when: certmanager.changed or flux.changed or pipelines.changed or rhacs.changed

- name: Add Cert Manager Cluster Issuer
  kubernetes.core.k8s:
    state: present
    template:
      - path: cluster-issuer.yaml.j2

- name: Add external-dns namespace
  kubernetes.core.k8s:
    state: present
    src: external-dns-namespace.yaml

- name: Add External-DNS
  kubernetes.core.k8s:
    state: present
    template:
      - path: external-dns.yaml.j2

- name: Add rhacs central
  kubernetes.core.k8s:
    state: present
    src: rhacs-central.yaml

- name: Add rhacs secured cluster
  kubernetes.core.k8s:
    state: present
    src: rhacs-secured-cluster.yaml