apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-hello-world
  namespace: openshift-gitops
spec:
  destination:
    namespace: hello-world-dev
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: environments/dev
    repoURL: 'https://gitlab.mays-demo.com/red-hat/hello-world-deploy.git'
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
