- name: Setup hello-world ci/cd demo
  hosts: localhost
  vars_files:
    - vars.yaml
  collections:
    - kubernetes.core
    - community.general
  roles:
    - operators
    - bigbang
    - demo-setup