cert_manager_email:
external_dns_config: |-
  - --source=openshift-route # ingress is also possible
  - --source=istio-virtualservice
  - --txt-prefix=external-dns. # In case of multiple k8s cluster
  - --openshift-router-name=default
  #ADD your environments specifics here