apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: flux
  namespace: flux-system
spec:
  channel: stable
  installPlanApproval: Automatic
  name: flux
  source: community-operators
  sourceNamespace: openshift-marketplace